/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:12
-- tzf::tzf_tzname
CREATE  FUNCTION "tzf_tzname"(
	"lon" double precision, /* f64 */
	"lat" double precision /* f64 */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tzf_tzname_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:17
-- tzf::tzf_tzname_point
CREATE  FUNCTION "tzf_tzname_point"(
	"point" point /* pgrx_pg_sys::include::pg15::Point */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tzf_tzname_point_wrapper';
/* </end connected objects> */

