/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:12
-- tzf::tzf_tzname
CREATE  FUNCTION "tzf_tzname"(
	"lon" double precision, /* f64 */
	"lat" double precision /* f64 */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tzf_tzname_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:24
-- tzf::tzf_tzname_batch
CREATE  FUNCTION "tzf_tzname_batch"(
	"lons" double precision[], /* alloc::vec::Vec<f64> */
	"lats" double precision[] /* alloc::vec::Vec<f64> */
) RETURNS TEXT[] /* alloc::vec::Vec<alloc::string::String> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tzf_tzname_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:36
-- tzf::tzf_tzname_batch_points
CREATE  FUNCTION "tzf_tzname_batch_points"(
	"points" point[] /* alloc::vec::Vec<pgrx_pg_sys::include::pg15::Point> */
) RETURNS TEXT[] /* alloc::vec::Vec<alloc::string::String> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tzf_tzname_batch_points_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:17
-- tzf::tzf_tzname_point
CREATE  FUNCTION "tzf_tzname_point"(
	"point" point /* pgrx_pg_sys::include::pg15::Point */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tzf_tzname_point_wrapper';
/* </end connected objects> */

