/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:11
-- tzf_pg::hello_tzf_pg
CREATE  FUNCTION "hello_tzf_pg"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'hello_tzf_pg_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:21
-- tzf_pg::tzf_tzname
CREATE  FUNCTION "tzf_tzname"(
	"lon" double precision, /* f64 */
	"lat" double precision /* f64 */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tzf_tzname_wrapper';
/* </end connected objects> */

